#if BACKEND_CURRENT == BACKEND_OPENGL

#include "glad.h"

#include "debugging/logger.h"
#include "graphics/backend/base/format_mapper.h"

int FormatMapper::map(const ImageFormat format)
{
	switch (format)
	{
	case ImageFormat::D16_UNORM:
		return GL_DEPTH_COMPONENT;

	case ImageFormat::D24_UNORM_S8_UINT:
	case ImageFormat::D32_SFLOAT_S8_UINT:
	case ImageFormat::D32_SFLOAT:
		return GL_DEPTH_STENCIL;

	case ImageFormat::R16_SFLOAT:
	case ImageFormat::R8_UINT:
	case ImageFormat::R8_SNORM:
	case ImageFormat::R8_SINT:
	case ImageFormat::R32_UINT:
	case ImageFormat::R32_SINT:
	case ImageFormat::R32_SFLOAT:
	case ImageFormat::R16_UINT:
	case ImageFormat::R16_SNORM:
	case ImageFormat::R16_SINT:
		return GL_RED;

	case ImageFormat::R16G16_SFLOAT:
	case ImageFormat::R8G8_UINT:
	case ImageFormat::R8G8_SNORM:
	case ImageFormat::R8G8_SINT:
	case ImageFormat::R32G32_UINT:
	case ImageFormat::R32G32_SINT:
	case ImageFormat::R32G32_SFLOAT:
	case ImageFormat::R16G16_UINT:
	case ImageFormat::R16G16_SNORM:
	case ImageFormat::R16G16_SINT:
		return GL_RG;

	case ImageFormat::R16G16B16_SFLOAT:
	case ImageFormat::R8G8B8_UINT:
	case ImageFormat::R8G8B8_SRGB:
	case ImageFormat::R8G8B8_SNORM:
	case ImageFormat::R8G8B8_SINT:
	case ImageFormat::R32G32B32_UINT:
	case ImageFormat::R32G32B32_SINT:
	case ImageFormat::R32G32B32_SFLOAT:
	case ImageFormat::R16G16B16_UINT:
	case ImageFormat::R16G16B16_SNORM:
	case ImageFormat::R16G16B16_SINT:
		return GL_RGB;

	case ImageFormat::R16G16B16A16_SFLOAT:
	case ImageFormat::R8G8B8A8_UINT:
	case ImageFormat::R8G8B8A8_SRGB:
	case ImageFormat::R8G8B8A8_SNORM:
	case ImageFormat::R8G8B8A8_SINT:
	case ImageFormat::R5G5B5A1_UNORM_PACK16:
	case ImageFormat::R4G4B4A4_UNORM_PACK16:
	case ImageFormat::R32G32B32A32_UINT:
	case ImageFormat::R32G32B32A32_SINT:
	case ImageFormat::R32G32B32A32_SFLOAT:
	case ImageFormat::R16G16B16A16_UINT:
	case ImageFormat::R16G16B16A16_SNORM:
	case ImageFormat::R16G16B16A16_SINT:
		return GL_RGBA;

	case ImageFormat::UNDEFINED:
	case ImageFormat::X8_D24_UNORM_PACK32:
	case ImageFormat::S8_UINT:
	case ImageFormat::R8G8B8A8_USCALED:
	case ImageFormat::R8G8B8A8_UNORM:
	case ImageFormat::R8G8B8A8_SSCALED:
	case ImageFormat::R8G8B8_USCALED:
	case ImageFormat::R8G8B8_UNORM:
	case ImageFormat::R8G8B8_SSCALED:
	case ImageFormat::R8G8_USCALED:
	case ImageFormat::R8G8_UNORM:
	case ImageFormat::R8G8_SSCALED:
	case ImageFormat::R8G8_SRGB:
	case ImageFormat::R8_USCALED:
	case ImageFormat::R8_UNORM:
	case ImageFormat::R8_SSCALED:
	case ImageFormat::R8_SRGB:
	case ImageFormat::R64G64B64A64_UINT:
	case ImageFormat::R64G64B64A64_SINT:
	case ImageFormat::R64G64B64A64_SFLOAT:
	case ImageFormat::R64G64B64_UINT:
	case ImageFormat::R64G64B64_SINT:
	case ImageFormat::R64G64B64_SFLOAT:
	case ImageFormat::R64G64_UINT:
	case ImageFormat::R64G64_SINT:
	case ImageFormat::R64G64_SFLOAT:
	case ImageFormat::R64_UINT:
	case ImageFormat::R64_SINT:
	case ImageFormat::R64_SFLOAT:
	case ImageFormat::R5G6B5_UNORM_PACK16:
	case ImageFormat::R4G4_UNORM_PACK8:
	case ImageFormat::R16G16B16A16_USCALED:
	case ImageFormat::R16G16B16A16_UNORM:
	case ImageFormat::R16G16B16A16_SSCALED:
	case ImageFormat::R16G16B16_USCALED:
	case ImageFormat::R16G16B16_UNORM:
	case ImageFormat::R16G16B16_SSCALED:
	case ImageFormat::R16G16_USCALED:
	case ImageFormat::R16G16_UNORM:
	case ImageFormat::R16G16_SSCALED:
	case ImageFormat::R16_USCALED:
	case ImageFormat::R16_UNORM:
	case ImageFormat::R16_SSCALED:
	case ImageFormat::ETC2_R8G8B8A8_UNORM_BLOCK:
	case ImageFormat::ETC2_R8G8B8A8_SRGB_BLOCK:
	case ImageFormat::ETC2_R8G8B8A1_UNORM_BLOCK:
	case ImageFormat::ETC2_R8G8B8A1_SRGB_BLOCK:
	case ImageFormat::ETC2_R8G8B8_UNORM_BLOCK:
	case ImageFormat::ETC2_R8G8B8_SRGB_BLOCK:
	case ImageFormat::EAC_R11G11_UNORM_BLOCK:
	case ImageFormat::EAC_R11G11_SNORM_BLOCK:
	case ImageFormat::EAC_R11_UNORM_BLOCK:
	case ImageFormat::EAC_R11_SNORM_BLOCK:
	case ImageFormat::E5B9G9R9_UFLOAT_PACK32:
	case ImageFormat::D16_UNORM_S8_UINT:
	case ImageFormat::BC7_UNORM_BLOCK:
	case ImageFormat::BC7_SRGB_BLOCK:
	case ImageFormat::BC6H_UFLOAT_BLOCK:
	case ImageFormat::BC6H_SFLOAT_BLOCK:
	case ImageFormat::BC5_UNORM_BLOCK:
	case ImageFormat::BC5_SNORM_BLOCK:
	case ImageFormat::BC4_UNORM_BLOCK:
	case ImageFormat::BC4_SNORM_BLOCK:
	case ImageFormat::BC3_UNORM_BLOCK:
	case ImageFormat::BC3_SRGB_BLOCK:
	case ImageFormat::BC2_UNORM_BLOCK:
	case ImageFormat::BC2_SRGB_BLOCK:
	case ImageFormat::BC1_RGBA_UNORM_BLOCK:
	case ImageFormat::BC1_RGBA_SRGB_BLOCK:
	case ImageFormat::BC1_RGB_UNORM_BLOCK:
	case ImageFormat::BC1_RGB_SRGB_BLOCK:
	case ImageFormat::B8G8R8A8_USCALED:
	case ImageFormat::B8G8R8A8_UNORM:
	case ImageFormat::B8G8R8A8_UINT:
	case ImageFormat::B8G8R8A8_SSCALED:
	case ImageFormat::B8G8R8A8_SRGB:
	case ImageFormat::B8G8R8A8_SNORM:
	case ImageFormat::B8G8R8A8_SINT:
	case ImageFormat::B8G8R8_USCALED:
	case ImageFormat::B8G8R8_UNORM:
	case ImageFormat::B8G8R8_UINT:
	case ImageFormat::B8G8R8_SSCALED:
	case ImageFormat::B8G8R8_SRGB:
	case ImageFormat::B8G8R8_SNORM:
	case ImageFormat::B8G8R8_SINT:
	case ImageFormat::B5G6R5_UNORM_PACK16:
	case ImageFormat::B5G5R5A1_UNORM_PACK16:
	case ImageFormat::B4G4R4A4_UNORM_PACK16:
	case ImageFormat::B10G11R11_UFLOAT_PACK32:
	case ImageFormat::ASTC_8X8_UNORM_BLOCK:
	case ImageFormat::ASTC_8X8_SRGB_BLOCK:
	case ImageFormat::ASTC_8X8_SFLOAT_BLOCK:
	case ImageFormat::ASTC_8X6_UNORM_BLOCK:
	case ImageFormat::ASTC_8X6_SRGB_BLOCK:
	case ImageFormat::ASTC_8X6_SFLOAT_BLOCK:
	case ImageFormat::ASTC_8X5_UNORM_BLOCK:
	case ImageFormat::ASTC_8X5_SRGB_BLOCK:
	case ImageFormat::ASTC_8X5_SFLOAT_BLOCK:
	case ImageFormat::ASTC_6X6_UNORM_BLOCK:
	case ImageFormat::ASTC_6X6_SRGB_BLOCK:
	case ImageFormat::ASTC_6X6_SFLOAT_BLOCK:
	case ImageFormat::ASTC_6X5_UNORM_BLOCK:
	case ImageFormat::ASTC_6X5_SRGB_BLOCK:
	case ImageFormat::ASTC_6X5_SFLOAT_BLOCK:
	case ImageFormat::ASTC_5X5_UNORM_BLOCK:
	case ImageFormat::ASTC_5X5_SRGB_BLOCK:
	case ImageFormat::ASTC_5X5_SFLOAT_BLOCK:
	case ImageFormat::ASTC_5X4_UNORM_BLOCK:
	case ImageFormat::ASTC_5X4_SRGB_BLOCK:
	case ImageFormat::ASTC_5X4_SFLOAT_BLOCK:
	case ImageFormat::ASTC_4X4_UNORM_BLOCK:
	case ImageFormat::ASTC_4X4_SRGB_BLOCK:
	case ImageFormat::ASTC_4X4_SFLOAT_BLOCK:
	case ImageFormat::ASTC_12X12_UNORM_BLOCK:
	case ImageFormat::ASTC_12X12_SRGB_BLOCK:
	case ImageFormat::ASTC_12X12_SFLOAT_BLOCK:
	case ImageFormat::ASTC_12X10_UNORM_BLOCK:
	case ImageFormat::ASTC_12X10_SRGB_BLOCK:
	case ImageFormat::ASTC_12X10_SFLOAT_BLOCK:
	case ImageFormat::ASTC_10X8_UNORM_BLOCK:
	case ImageFormat::ASTC_10X8_SRGB_BLOCK:
	case ImageFormat::ASTC_10X8_SFLOAT_BLOCK:
	case ImageFormat::ASTC_10X6_UNORM_BLOCK:
	case ImageFormat::ASTC_10X6_SRGB_BLOCK:
	case ImageFormat::ASTC_10X6_SFLOAT_BLOCK:
	case ImageFormat::ASTC_10X5_UNORM_BLOCK:
	case ImageFormat::ASTC_10X5_SRGB_BLOCK:
	case ImageFormat::ASTC_10X5_SFLOAT_BLOCK:
	case ImageFormat::ASTC_10X10_UNORM_BLOCK:
	case ImageFormat::ASTC_10X10_SRGB_BLOCK:
	case ImageFormat::ASTC_10X10_SFLOAT_BLOCK:
	case ImageFormat::A8B8G8R8_USCALED_PACK32:
	case ImageFormat::A8B8G8R8_UNORM_PACK32:
	case ImageFormat::A8B8G8R8_UINT_PACK32:
	case ImageFormat::A8B8G8R8_SSCALED_PACK32:
	case ImageFormat::A8B8G8R8_SRGB_PACK32:
	case ImageFormat::A8B8G8R8_SNORM_PACK32:
	case ImageFormat::A8B8G8R8_SINT_PACK32:
	case ImageFormat::A8_UNORM:
	case ImageFormat::A4R4G4B4_UNORM_PACK16:
	case ImageFormat::A4B4G4R4_UNORM_PACK16:
	case ImageFormat::A2R10G10B10_USCALED_PACK32:
	case ImageFormat::A2R10G10B10_UNORM_PACK32:
	case ImageFormat::A2R10G10B10_UINT_PACK32:
	case ImageFormat::A2R10G10B10_SSCALED_PACK32:
	case ImageFormat::A2R10G10B10_SNORM_PACK32:
	case ImageFormat::A2R10G10B10_SINT_PACK32:
	case ImageFormat::A2B10G10R10_USCALED_PACK32:
	case ImageFormat::A2B10G10R10_UNORM_PACK32:
	case ImageFormat::A2B10G10R10_UINT_PACK32:
	case ImageFormat::A2B10G10R10_SSCALED_PACK32:
	case ImageFormat::A2B10G10R10_SNORM_PACK32:
	case ImageFormat::A2B10G10R10_SINT_PACK32:
	case ImageFormat::A1R5G5B5_UNORM_PACK16:
	default:
		LOG_FATAL("Invalid image format specified");
		return -1;
	}
}

int FormatMapper::map_type(const ImageFormat format)
{
	switch (format)
	{
	case ImageFormat::D16_UNORM:
	case ImageFormat::R16G16B16A16_UINT:
	case ImageFormat::R16G16B16_UINT:
	case ImageFormat::R16G16_UINT:
	case ImageFormat::R16_UINT:
		return GL_UNSIGNED_SHORT;

	case ImageFormat::D24_UNORM_S8_UINT:
	case ImageFormat::R32G32B32A32_UINT:
	case ImageFormat::R32G32B32_UINT:
	case ImageFormat::R32G32_UINT:
	case ImageFormat::R32_UINT:
	case ImageFormat::D32_SFLOAT_S8_UINT:
		return GL_UNSIGNED_INT;

	case ImageFormat::D32_SFLOAT:
	case ImageFormat::R32G32B32A32_SINT:
	case ImageFormat::R32G32B32_SINT:
	case ImageFormat::R32G32_SINT:
	case ImageFormat::R32_SINT:
		return GL_INT;

	case ImageFormat::R16_SFLOAT:
	case ImageFormat::R32G32B32A32_SFLOAT:
	case ImageFormat::R32G32B32_SFLOAT:
	case ImageFormat::R32G32_SFLOAT:
	case ImageFormat::R32_SFLOAT:
	case ImageFormat::R16G16B16A16_SFLOAT:
	case ImageFormat::R16G16B16_SFLOAT:
	case ImageFormat::R16G16_SFLOAT:
		return GL_FLOAT;

	case ImageFormat::R16_SINT:
	case ImageFormat::R16G16B16A16_SNORM:
	case ImageFormat::R16G16B16A16_SINT:
	case ImageFormat::R16G16B16_SNORM:
	case ImageFormat::R16G16B16_SINT:
	case ImageFormat::R16G16_SNORM:
	case ImageFormat::R16G16_SINT:
	case ImageFormat::R16_SNORM:
		return GL_SHORT;

	case ImageFormat::R4G4B4A4_UNORM_PACK16:
		return GL_UNSIGNED_SHORT_4_4_4_4;

	case ImageFormat::R5G5B5A1_UNORM_PACK16:
		return GL_UNSIGNED_SHORT_5_5_5_1;

	case ImageFormat::R8_SINT:
	case ImageFormat::R8G8B8A8_SRGB:
	case ImageFormat::R8G8B8A8_SNORM:
	case ImageFormat::R8G8B8A8_SINT:
	case ImageFormat::R8G8B8_SNORM:
	case ImageFormat::R8G8B8_SINT:
	case ImageFormat::R8G8_SNORM:
	case ImageFormat::R8G8_SINT:
	case ImageFormat::R8_SNORM:
		return GL_BYTE;

	case ImageFormat::R8_UINT:
	case ImageFormat::R8G8B8_UINT:
	case ImageFormat::R8G8B8A8_UINT:
	case ImageFormat::R8G8_UINT:
		return GL_UNSIGNED_BYTE;

	case ImageFormat::R8G8B8_SRGB:
		return GL_SRGB8;

	case ImageFormat::UNDEFINED:
	case ImageFormat::X8_D24_UNORM_PACK32:
	case ImageFormat::S8_UINT:
	case ImageFormat::R8G8B8A8_USCALED:
	case ImageFormat::R8G8B8A8_UNORM:
	case ImageFormat::R8G8B8A8_SSCALED:
	case ImageFormat::R8G8B8_USCALED:
	case ImageFormat::R8G8B8_UNORM:
	case ImageFormat::R8G8B8_SSCALED:
	case ImageFormat::R8G8_USCALED:
	case ImageFormat::R8G8_UNORM:
	case ImageFormat::R8G8_SSCALED:
	case ImageFormat::R8G8_SRGB:
	case ImageFormat::R8_USCALED:
	case ImageFormat::R8_UNORM:
	case ImageFormat::R8_SSCALED:
	case ImageFormat::R8_SRGB:
	case ImageFormat::R64G64B64A64_UINT:
	case ImageFormat::R64G64B64A64_SINT:
	case ImageFormat::R64G64B64A64_SFLOAT:
	case ImageFormat::R64G64B64_UINT:
	case ImageFormat::R64G64B64_SINT:
	case ImageFormat::R64G64B64_SFLOAT:
	case ImageFormat::R64G64_UINT:
	case ImageFormat::R64G64_SINT:
	case ImageFormat::R64G64_SFLOAT:
	case ImageFormat::R64_UINT:
	case ImageFormat::R64_SINT:
	case ImageFormat::R64_SFLOAT:
	case ImageFormat::R5G6B5_UNORM_PACK16:
	case ImageFormat::R4G4_UNORM_PACK8:
	case ImageFormat::R16G16B16A16_USCALED:
	case ImageFormat::R16G16B16A16_UNORM:
	case ImageFormat::R16G16B16A16_SSCALED:
	case ImageFormat::R16G16B16_USCALED:
	case ImageFormat::R16G16B16_UNORM:
	case ImageFormat::R16G16B16_SSCALED:
	case ImageFormat::R16G16_USCALED:
	case ImageFormat::R16G16_UNORM:
	case ImageFormat::R16G16_SSCALED:
	case ImageFormat::R16_USCALED:
	case ImageFormat::R16_UNORM:
	case ImageFormat::R16_SSCALED:
	case ImageFormat::ETC2_R8G8B8A8_UNORM_BLOCK:
	case ImageFormat::ETC2_R8G8B8A8_SRGB_BLOCK:
	case ImageFormat::ETC2_R8G8B8A1_UNORM_BLOCK:
	case ImageFormat::ETC2_R8G8B8A1_SRGB_BLOCK:
	case ImageFormat::ETC2_R8G8B8_UNORM_BLOCK:
	case ImageFormat::ETC2_R8G8B8_SRGB_BLOCK:
	case ImageFormat::EAC_R11G11_UNORM_BLOCK:
	case ImageFormat::EAC_R11G11_SNORM_BLOCK:
	case ImageFormat::EAC_R11_UNORM_BLOCK:
	case ImageFormat::EAC_R11_SNORM_BLOCK:
	case ImageFormat::E5B9G9R9_UFLOAT_PACK32:
	case ImageFormat::D16_UNORM_S8_UINT:
	case ImageFormat::BC7_UNORM_BLOCK:
	case ImageFormat::BC7_SRGB_BLOCK:
	case ImageFormat::BC6H_UFLOAT_BLOCK:
	case ImageFormat::BC6H_SFLOAT_BLOCK:
	case ImageFormat::BC5_UNORM_BLOCK:
	case ImageFormat::BC5_SNORM_BLOCK:
	case ImageFormat::BC4_UNORM_BLOCK:
	case ImageFormat::BC4_SNORM_BLOCK:
	case ImageFormat::BC3_UNORM_BLOCK:
	case ImageFormat::BC3_SRGB_BLOCK:
	case ImageFormat::BC2_UNORM_BLOCK:
	case ImageFormat::BC2_SRGB_BLOCK:
	case ImageFormat::BC1_RGBA_UNORM_BLOCK:
	case ImageFormat::BC1_RGBA_SRGB_BLOCK:
	case ImageFormat::BC1_RGB_UNORM_BLOCK:
	case ImageFormat::BC1_RGB_SRGB_BLOCK:
	case ImageFormat::B8G8R8A8_USCALED:
	case ImageFormat::B8G8R8A8_UNORM:
	case ImageFormat::B8G8R8A8_UINT:
	case ImageFormat::B8G8R8A8_SSCALED:
	case ImageFormat::B8G8R8A8_SRGB:
	case ImageFormat::B8G8R8A8_SNORM:
	case ImageFormat::B8G8R8A8_SINT:
	case ImageFormat::B8G8R8_USCALED:
	case ImageFormat::B8G8R8_UNORM:
	case ImageFormat::B8G8R8_UINT:
	case ImageFormat::B8G8R8_SSCALED:
	case ImageFormat::B8G8R8_SRGB:
	case ImageFormat::B8G8R8_SNORM:
	case ImageFormat::B8G8R8_SINT:
	case ImageFormat::B5G6R5_UNORM_PACK16:
	case ImageFormat::B5G5R5A1_UNORM_PACK16:
	case ImageFormat::B4G4R4A4_UNORM_PACK16:
	case ImageFormat::B10G11R11_UFLOAT_PACK32:
	case ImageFormat::ASTC_8X8_UNORM_BLOCK:
	case ImageFormat::ASTC_8X8_SRGB_BLOCK:
	case ImageFormat::ASTC_8X8_SFLOAT_BLOCK:
	case ImageFormat::ASTC_8X6_UNORM_BLOCK:
	case ImageFormat::ASTC_8X6_SRGB_BLOCK:
	case ImageFormat::ASTC_8X6_SFLOAT_BLOCK:
	case ImageFormat::ASTC_8X5_UNORM_BLOCK:
	case ImageFormat::ASTC_8X5_SRGB_BLOCK:
	case ImageFormat::ASTC_8X5_SFLOAT_BLOCK:
	case ImageFormat::ASTC_6X6_UNORM_BLOCK:
	case ImageFormat::ASTC_6X6_SRGB_BLOCK:
	case ImageFormat::ASTC_6X6_SFLOAT_BLOCK:
	case ImageFormat::ASTC_6X5_UNORM_BLOCK:
	case ImageFormat::ASTC_6X5_SRGB_BLOCK:
	case ImageFormat::ASTC_6X5_SFLOAT_BLOCK:
	case ImageFormat::ASTC_5X5_UNORM_BLOCK:
	case ImageFormat::ASTC_5X5_SRGB_BLOCK:
	case ImageFormat::ASTC_5X5_SFLOAT_BLOCK:
	case ImageFormat::ASTC_5X4_UNORM_BLOCK:
	case ImageFormat::ASTC_5X4_SRGB_BLOCK:
	case ImageFormat::ASTC_5X4_SFLOAT_BLOCK:
	case ImageFormat::ASTC_4X4_UNORM_BLOCK:
	case ImageFormat::ASTC_4X4_SRGB_BLOCK:
	case ImageFormat::ASTC_4X4_SFLOAT_BLOCK:
	case ImageFormat::ASTC_12X12_UNORM_BLOCK:
	case ImageFormat::ASTC_12X12_SRGB_BLOCK:
	case ImageFormat::ASTC_12X12_SFLOAT_BLOCK:
	case ImageFormat::ASTC_12X10_UNORM_BLOCK:
	case ImageFormat::ASTC_12X10_SRGB_BLOCK:
	case ImageFormat::ASTC_12X10_SFLOAT_BLOCK:
	case ImageFormat::ASTC_10X8_UNORM_BLOCK:
	case ImageFormat::ASTC_10X8_SRGB_BLOCK:
	case ImageFormat::ASTC_10X8_SFLOAT_BLOCK:
	case ImageFormat::ASTC_10X6_UNORM_BLOCK:
	case ImageFormat::ASTC_10X6_SRGB_BLOCK:
	case ImageFormat::ASTC_10X6_SFLOAT_BLOCK:
	case ImageFormat::ASTC_10X5_UNORM_BLOCK:
	case ImageFormat::ASTC_10X5_SRGB_BLOCK:
	case ImageFormat::ASTC_10X5_SFLOAT_BLOCK:
	case ImageFormat::ASTC_10X10_UNORM_BLOCK:
	case ImageFormat::ASTC_10X10_SRGB_BLOCK:
	case ImageFormat::ASTC_10X10_SFLOAT_BLOCK:
	case ImageFormat::A8B8G8R8_USCALED_PACK32:
	case ImageFormat::A8B8G8R8_UNORM_PACK32:
	case ImageFormat::A8B8G8R8_UINT_PACK32:
	case ImageFormat::A8B8G8R8_SSCALED_PACK32:
	case ImageFormat::A8B8G8R8_SRGB_PACK32:
	case ImageFormat::A8B8G8R8_SNORM_PACK32:
	case ImageFormat::A8B8G8R8_SINT_PACK32:
	case ImageFormat::A8_UNORM:
	case ImageFormat::A4R4G4B4_UNORM_PACK16:
	case ImageFormat::A4B4G4R4_UNORM_PACK16:
	case ImageFormat::A2R10G10B10_USCALED_PACK32:
	case ImageFormat::A2R10G10B10_UNORM_PACK32:
	case ImageFormat::A2R10G10B10_UINT_PACK32:
	case ImageFormat::A2R10G10B10_SSCALED_PACK32:
	case ImageFormat::A2R10G10B10_SNORM_PACK32:
	case ImageFormat::A2R10G10B10_SINT_PACK32:
	case ImageFormat::A2B10G10R10_USCALED_PACK32:
	case ImageFormat::A2B10G10R10_UNORM_PACK32:
	case ImageFormat::A2B10G10R10_UINT_PACK32:
	case ImageFormat::A2B10G10R10_SSCALED_PACK32:
	case ImageFormat::A2B10G10R10_SNORM_PACK32:
	case ImageFormat::A2B10G10R10_SINT_PACK32:
	case ImageFormat::A1R5G5B5_UNORM_PACK16:
	default:
		LOG_FATAL("Invalid image format specified");
		return -1;
	}
}
#endif